# Generated by Django 5.0.4 on 2024-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_libraryuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookborrow',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='userId',
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='username',
            field=models.CharField(default='bavly', max_length=255),
            preserve_default=False,
        ),
    ]
